### ISSUE TITLE
BrowserCookie detect does not work with 14.0.0.beta2

### ISSUE THREAD

**Issue by sirbris** [viritin/flow-viritin#16]
I try to read a cookie in my UI class:
`BrowserCookie.detectCookieValue("user", new Callback() {
            @Override
            public void onValueDetected(String inValue) {
                System.out.println(inValue);
            }
        });`
I get following error:
(TypeError) : $0.readCookie is not a function

**Comment by mstahv** [comment]
Now fixed, will create a new version to the Directory soon.
